# Generated by Django 4.2.4 on 2023-09-11 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_status'),
        ('blog', '0003_alter_blog_status'),
    ]

    operations = [
    ]
