# Generated by Django 4.2.4 on 2023-09-13 14:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Commentt',
        ),
    ]
